{{- if and (not .Values.remote.enabled) .Values.networkPolicy (index .Values.networkPolicy "enabled") -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "janus.fullname" . }}-controller
  namespace: {{ .Values.janus.namespace }}
  labels:
    {{- include "janus.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "janus.controller.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - port: 8080  # healthz
  egress:
    - ports:
        - port: 443   # Kubernetes API
        - port: 6443  # Kubernetes API (alternate)
    - ports:
        - port: 53    # DNS
          protocol: UDP
        - port: 53
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "janus.fullname" . }}-webui
  namespace: {{ .Values.janus.namespace }}
  labels:
    {{- include "janus.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "janus.webui.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - port: {{ .Values.webui.containerPort }}  # web UI
  egress:
    - ports:
        - port: 443   # Kubernetes API
        - port: 6443  # Kubernetes API (alternate)
    - ports:
        - port: 53    # DNS
          protocol: UDP
        - port: 53
          protocol: TCP
{{- end }}
