{{- if and .Values.postgresql.enabled .Values.externalSecrets.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "janus.fullname" . }}-postgresql
  namespace: {{ .Values.janus.namespace }}
  labels:
    {{- include "janus.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1h" }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecrets.secretStore }}
  target:
    name: {{ include "janus.fullname" . }}-postgresql
    creationPolicy: Owner
  data:
  - secretKey: password
    remoteRef:
      key: {{ .Values.postgresql.secretKey | default "K8S-JANUS-DB-PASSWORD" }}
{{- end }}
