---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "janus.controller.name" . }}
  namespace: {{ .Values.janus.namespace }}
  labels:
    {{- include "janus.labels" . | nindent 4 }}
automountServiceAccountToken: true

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "janus.webui.name" . }}
  namespace: {{ .Values.janus.namespace }}
  labels:
    {{- include "janus.labels" . | nindent 4 }}
automountServiceAccountToken: true
