{{- if not .Values.remote.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "janus.webui.name" . }}
  namespace: {{ .Values.janus.namespace }}
  {{- if .Values.service.externalDnsHostname }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.service.externalDnsHostname | quote }}
  {{- end }}
  labels:
    {{- include "janus.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP | quote }}
  {{- end }}
  selector:
    {{- include "janus.webui.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.webui.containerPort }}
      protocol: TCP
{{- end }}
