apiVersion: v2
name: k8s-janus
description: "K8s-Janus â€” God of Gateways. Just-in-Time Kubernetes pod access with approval workflow."
type: application
version: 0.1.8
appVersion: "0.1.8"
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Initial release
keywords:
  - kubernetes
  - k8s-janus
  - rbac
  - access-control
  - security
  - jit
  - zero-trust
icon: https://raw.githubusercontent.com/opsmode/k8s-janus/main/webui/static/k8s-janus-logo-readme.png
home: https://github.com/opsmode/k8s-janus
sources:
  - https://github.com/opsmode/k8s-janus
maintainers:
  - name: OpsMode
    email: devops@opsmode.io
